/* Hance Auditorium touch panel, rebuilt for the web from Hance UCI.uci.
 *
 * Layout, z-order, labels, CSS classes and control bindings come from the UCI file (see hance.json,
 * generated by to_sim.py). A UCI file carries no logic: the Core's Lua scripts decide what each
 * button does and which layers show. The behavior below is inferred from the layer names, the
 * control names and how Q-SYS panels usually work, and is marked INFERRED where it matters.
 *
 * mountUCISim(screenEl, { scene, status, reduced }) -> Promise<api>
 *   scene   optional sceneApi from the 3D page (setProjector, setScreenDeployed, cameraFeed, setVolume)
 *   status  optional element that gets a plain-language readout of the simulated room
 */
const BASE = new URL('./', import.meta.url);
const W = 1920, H = 1200;

const ICON = {
  'arrow-up': '<path d="M5 15.5l7-7 7 7"/>', 'arrow-down': '<path d="M5 8.5l7 7 7-7"/>',
  'arrow-left': '<path d="M15.5 5l-7 7 7 7"/>', 'arrow-right': '<path d="M8.5 5l7 7-7 7"/>',
  'zoom-in': '<circle cx="10.5" cy="10.5" r="6.5"/><path d="M15.3 15.3L20 20M10.5 7.8v5.4M7.8 10.5h5.4"/>',
  'zoom-out': '<circle cx="10.5" cy="10.5" r="6.5"/><path d="M15.3 15.3L20 20M7.8 10.5h5.4"/>',
  power: '<path d="M12 3.5v8"/><path d="M7.1 6.8a7.2 7.2 0 1 0 9.8 0"/>',
  'nav-sources': '<rect x="4" y="5" width="16" height="10.5" rx="1.6"/><path d="M2.5 19h19"/>',
  'nav-room': '<rect x="3" y="4" width="18" height="12" rx="1.6"/><path d="M8.5 20h7M12 16v4"/>',
  'nav-audio': '<path d="M4 9.5h3.4L12 5.8v12.4l-4.6-3.7H4z"/><path d="M15.6 9.2a4 4 0 0 1 0 5.6M18.2 6.6a7.6 7.6 0 0 1 0 10.8"/>',
  'nav-cameras': '<rect x="2.8" y="6.8" width="12.4" height="10.4" rx="2"/><path d="M15.2 11l5.6-3.4v8.8L15.2 13z"/>',
};
const svg = (name, px, sw = 2.1) => `<svg viewBox="0 0 24 24" width="${px}" height="${px}" stroke-width="${sw}" aria-hidden="true">${ICON[name]}</svg>`;

const SRC = { pc: 'Lectern PC', laptop: 'Laptop', zoom: 'Zoom Wireless' };
const DISP = { proj: 'Projector', left: 'Left display', right: 'Right display' };
const PAGE = { sources: 'Sources', room: 'Room', audio: 'Audio', cameras: 'Cameras' };
const CAMS = { audience: { view: 'rallya', name: 'Audience', tag: 'Audience · Rally A, front of room' },
               presenter: { view: 'rallyb', name: 'Presenter', tag: 'Presenter · Rally B, back of room' } };
// INFERRED timings, shortened for the web. A real projector takes closer to 30 seconds to warm up.
const T = { sysWarm: 5000, sysCool: 4000, disp: { proj: [4000, 3000], left: [2000, 1500], right: [2000, 1500] }, hold: 2000, saved: 2000 };
const PTZ = { panMax: 90, tiltMin: -35, tiltMax: 30, zoomMax: 5, panRate: 32, tiltRate: 22, zoomRate: 1.9 };
const DB = { min: -60, max: 20 };
const ptz0 = () => ({ pan: 0, tilt: 0, zoom: 1 });
const presets0 = () => [{ pan: 22, tilt: -2, zoom: 1.5 }, ptz0(), { pan: -22, tilt: -2, zoom: 1.5 }, ptz0()];

const LABEL = {   // accessible names for icon-only and invisible controls
  'vol.mute': 'Mute room volume', 'zoom.micmute': 'Mute Zoom microphone', 'mic.lapel.mute': 'Mute lapel mic',
  'mic.handheld.mute': 'Mute handheld mic', 'mic.ceiling.mute': 'Mute ceiling mic', 'screen.up': 'Screen up', 'screen.down': 'Screen down',
  'cam.ptz.zoom_out': 'Zoom out', 'cam.ptz.zoom_in': 'Zoom in', 'cam.ptz.tilt_up': 'Tilt up', 'cam.ptz.tilt_down': 'Tilt down',
  'cam.ptz.pan_left': 'Pan left', 'cam.ptz.pan_right': 'Pan right', 'nav.sources': 'Sources', 'nav.room': 'Room controls',
  'nav.audio': 'Audio', 'nav.cameras': 'Cameras', 'sys.start': 'Tap here to start the system', 'help.hide': 'Close help',
  'sys.off': 'System off', 'vol.gain': 'Room volume', 'mic.lapel.gain': 'Lapel mic level', 'mic.handheld.gain': 'Handheld mic level',
};

function fresh() {
  return {
    power: 'off', sysP: 0, mode: 'simple', page: 'sources',
    help: false, helpNow: false, shutdown: false, presetSaved: false, mixer: false,
    videoMute: false, camMute: false, privacy: false,
    routes: { proj: 'pc', left: 'pc', right: 'pc' },
    disp: { proj: { on: false, busy: 0, p: 0 }, left: { on: false, busy: 0, p: 0 }, right: { on: false, busy: 0, p: 0 } },
    screen: 'down',
    vol: { gain: -5.26, mute: false }, zoomMicMute: false,
    mic: { lapel: { gain: 4.59, mute: false }, handheld: { gain: 4.75, mute: false }, ceiling: { mute: false } },
    cam: { sel: 'presenter', ptz: { audience: ptz0(), presenter: ptz0() }, presets: { audience: presets0(), presenter: presets0() } },
  };
}

export async function mountUCISim(screen, opts = {}) {
  const scene = opts.scene || null, statusEl = opts.status || null;
  const reduced = opts.reduced || (() => matchMedia('(prefers-reduced-motion: reduce)').matches);
  if (!document.querySelector('link[data-uci-css]')) {
    const l = document.createElement('link'); l.rel = 'stylesheet'; l.href = new URL('sim.css', BASE).href; l.dataset.uciCss = '';
    document.head.appendChild(l);
  }
  const model = await fetch(new URL('hance.json', BASE)).then(r => { if (!r.ok) throw new Error('hance.json ' + r.status); return r.json(); });

  /* ---------------------------------------------------------------- build the stage */
  screen.classList.add('uci-screen');
  screen.innerHTML = '';
  const stage = document.createElement('div'); stage.className = 'uci-stage';
  stage.setAttribute('role', 'group'); stage.setAttribute('aria-label', model.title + ' touch panel, simulated');
  screen.appendChild(stage);
  const layerEl = {}, byBind = new Map(), faders = [], meters = [];
  const N = model.layers.length;
  let mediaEl = null, mediaMsg = null, mediaTag = null;

  model.layers.forEach((L, i) => {
    const le = document.createElement('div'); le.className = 'uci-layer'; le.dataset.layer = L.key;
    le.style.zIndex = String((N - i) * 10);         // layers[0] is the top of the Designer stack
    layerEl[L.key] = le;
    for (const e of L.els) {
      const el = make(e, L.key);
      if (!el) continue;
      let { x, y, w, h } = e;
      if (e.cls === 'buttonNav') { x += 10; y += 10; w -= 20; h -= 20; }   // stylesheet margin: 10px
      el.style.left = x + 'px'; el.style.top = y + 'px'; el.style.width = w + 'px'; el.style.height = h + 'px';
      el.style.zIndex = String(e.z || 0);
      if (e.bind) { el.dataset.bind = e.bind; if (!byBind.has(e.bind)) byBind.set(e.bind, []); byBind.get(e.bind).push(el); }
      le.appendChild(el);
    }
    stage.appendChild(le);
  });
  const toastEl = document.createElement('div'); toastEl.className = 'uci-toast'; toastEl.setAttribute('role', 'status'); stage.appendChild(toastEl);

  function make(e, layer) {
    let el;
    const cls = e.cls || '';
    switch (e.t) {
      case 'text':
        el = document.createElement('div'); el.className = `u t ha${e.ha} ${cls || 'plain'}`; el.textContent = e.label;
        if (!cls) { el.style.color = e.color; el.style.fontSize = e.fs + 'px'; }
        return el;
      case 'group':
        el = document.createElement('div'); el.className = 'u g ' + cls;
        if (e.fill) el.style.background = e.fill;
        if (cls === 'backgroundoverlayWhite') el.style.pointerEvents = 'auto';   // card swallows taps so they don't hit the backdrop
        return el;
      case 'image':
        el = document.createElement('img'); el.className = 'u'; el.src = new URL('img/' + e.src, BASE).href; el.alt = '';
        el.draggable = false; if (layer === 'help') el.style.pointerEvents = 'auto';
        if (e.src === 'help_qr.jpg') { el.alt = 'QR code for submitting a help ticket'; }
        return el;
      case 'mask':
        el = document.createElement('div'); el.className = 'u mask' + (layer === 'warm' || layer === 'cool' ? ' dim' : '');
        el.setAttribute('aria-hidden', 'true'); return el;
      case 'meter':
        el = document.createElement('div'); el.className = 'u m' + (layer === 'warm' || layer === 'cool' ? ' dark' : '');
        el.setAttribute('role', 'progressbar'); el.setAttribute('aria-valuemin', '0'); el.setAttribute('aria-valuemax', '100');
        el.appendChild(document.createElement('i')); meters.push(el); return el;
      case 'media':
        el = document.createElement('div'); el.className = 'u media';
        el.innerHTML = '<div class="msg"></div><span class="tag"></span>';
        mediaEl = el; mediaMsg = el.querySelector('.msg'); mediaTag = el.querySelector('.tag'); return el;
      case 'fader': {
        el = document.createElement('div'); el.className = 'u f'; el.tabIndex = 0; el.setAttribute('role', 'slider');
        el.setAttribute('aria-valuemin', String(DB.min)); el.setAttribute('aria-valuemax', String(DB.max));
        el.setAttribute('aria-label', LABEL[e.bind] || e.bind);
        el.innerHTML = '<div class="f-slot"><div class="f-fill"></div></div><div class="f-cap"></div>';
        faders.push(el); wireFader(el, e.bind); return el;
      }
      case 'button': {
        el = document.createElement('button'); el.type = 'button'; el.className = 'u ' + cls;
        el.dataset.kind = e.kind;
        if (e.icon) el.innerHTML = svg(e.icon, e.bind === 'sys.off' ? 70 : e.bind.startsWith('nav.') ? 54 : 78, e.bind.startsWith('cam.ptz') ? 2.4 : 2);
        if (e.label) el.insertAdjacentHTML('beforeend', `<span>${esc(e.label)}</span>`);
        const name = LABEL[e.bind]; if (name && !e.label) el.setAttribute('aria-label', name);
        if (e.bind === 'sys.off') el.setAttribute('aria-label', 'System off');
        if (e.bind === 'mode.toggle') el.classList.add('hotspot');
        const backdrop = (e.bind === 'help.hide' || e.bind === 'shutdown.cancel') && e.w === W && e.h === H;
        if (backdrop) { el.tabIndex = -1; el.setAttribute('aria-hidden', 'true'); el.style.cursor = 'default'; }
        if (e.kind === 'toggle') el.setAttribute('aria-pressed', 'false');
        wireButton(el, e.bind, e.kind);
        return el;
      }
    }
    return null;
  }
  function esc(s) { return String(s).replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c]); }

  /* ---------------------------------------------------------------- scale to fit */
  const fit = () => { const k = screen.clientWidth / W; stage.style.transform = `scale(${k})`; stage.dataset.k = k.toFixed(4); };
  new ResizeObserver(fit).observe(screen); fit();

  /* ---------------------------------------------------------------- state */
  let S = fresh();
  let engaged = false;                    // the 3D model follows the panel only after someone uses it
  const pressed = new Set();              // controls currently held down (momentary/trigger feedback)
  const moving = new Set();               // PTZ directions being held
  let holdTimer = null, holdSaved = false, savedTimer = null, toastTimer = null;
  let sysAnim = null, recall = null;
  const listeners = new Set();

  function engage() { if (!engaged) { engaged = true; } }
  screen.addEventListener('pointerdown', engage, true);
  screen.addEventListener('keydown', engage, true);

  function toast(html, ms = 3600) {
    toastEl.innerHTML = html; toastEl.classList.add('show');
    clearTimeout(toastTimer); toastTimer = setTimeout(() => toastEl.classList.remove('show'), ms);
  }
  const db = g => (g > 0 ? '+' : g < 0 ? '−' : '') + Math.abs(g).toFixed(1) + ' dB';
  const pOf = g => Math.max(0, Math.min(1, (g - DB.min) / (DB.max - DB.min)));
  const gOf = p => Math.round((DB.min + p * (DB.max - DB.min)) * 10) / 10;

  /* ---------------------------------------------------------------- actions */
  function act(bind, down) {
    const [a, b, c] = bind.split('.');
    // momentary controls first: they care about press and release
    if (a === 'cam' && b === 'ptz') { down ? moving.add(c) : moving.delete(c); if (down) recall = null; kick(); return; }
    if (a === 'cam' && b === 'preset') { presetPress(+c - 1, down); return; }
    if (down === false) return;
    switch (a) {
      case 'sys':
        if (b === 'start' && S.power === 'off') startSystem();
        if (b === 'off' && S.power === 'on') S.shutdown = true;
        break;
      case 'shutdown':
        S.shutdown = false;
        if (b === 'confirm') stopSystem();
        break;
      case 'help':
        if (b === 'show') S.help = true;
        else if (b === 'hide') S.help = false;
        else if (b === 'now') { S.helpNow = !S.helpNow; if (S.helpNow) toast('<b>Simulated.</b> On the real panel, Yes would alert the help desk. Nothing was sent.'); }
        else toast(`<b>Simulated.</b> On the real panel this would report ${b === 'av' ? 'an audio/video' : 'a network'} issue to the help desk. Nothing was sent.`);
        break;
      case 'mode':
        S.mode = S.mode === 'simple' ? 'advanced' : 'simple';
        if (S.mode === 'advanced') S.page = 'sources';
        else { S.mixer = false; recallPreset(3, true); }       // INFERRED: preset 4 is labeled "Simple Mode"
        break;
      case 'nav': S.page = b; break;
      case 'route':
        if (b === 'all') for (const d of Object.keys(S.routes)) S.routes[d] = c;
        else S.routes[b] = c;
        break;
      case 'disp': dispPower(b, c === 'on'); break;
      case 'screen': S.screen = b; break;
      case 'vol': if (b === 'mute') S.vol.mute = !S.vol.mute; break;
      case 'zoom': S.zoomMicMute = !S.zoomMicMute; break;
      case 'mic': if (c === 'mute') S.mic[b].mute = !S.mic[b].mute; break;
      case 'mixer': S.mixer = b === 'enter'; break;
      case 'cam':
        if (b === 'sel') { S.cam.sel = c; recall = null; }
        if (b === 'privacy') S.privacy = !S.privacy;
        break;
      case 'av':
        if (b === 'videomute') S.videoMute = !S.videoMute;
        if (b === 'cammute') S.camMute = !S.camMute;
        break;
    }
    render();
  }

  function startSystem() {       // INFERRED: Splash tap powers the room on, shows Warm with a progress bar, then Simple
    S.power = 'warming'; S.sysP = 0; S.shutdown = false; S.help = false;
    animate(T.sysWarm, p => { S.sysP = p; }, () => {
      S.power = 'on'; S.mode = 'simple'; S.page = 'sources'; S.screen = 'down';
      for (const d of Object.keys(S.disp)) Object.assign(S.disp[d], { on: true, busy: 0, p: 0 });
      for (const d of Object.keys(S.routes)) S.routes[d] = 'pc';
      recallPreset(3, true, true);
    });
  }
  function stopSystem() {        // INFERRED: Power Off shows Cool, turns everything off and returns to Splash
    S.power = 'cooling'; S.sysP = 0; S.help = false;
    for (const d of Object.keys(S.disp)) Object.assign(S.disp[d], { on: false, busy: 0, p: 0 });
    S.screen = 'up';
    animate(T.sysCool, p => { S.sysP = p; }, () => {
      const keep = { vol: S.vol, mic: S.mic, presets: S.cam.presets };
      S = fresh(); S.vol = keep.vol; S.mic = keep.mic; S.cam.presets = keep.presets; S.screen = 'up';
    });
  }
  function dispPower(d, on) {    // INFERRED: Off/On hide while the device warms or cools and the Progress meter shows instead
    const D = S.disp[d]; if (D.busy || D.on === on || S.power !== 'on') return;
    D.busy = on ? 1 : -1; D.p = 0;
    const [tw, tc] = T.disp[d];
    animate(on ? tw : tc, p => { D.p = p; }, () => { D.busy = 0; D.p = 0; D.on = on; });
  }
  const anims = new Set();
  function animate(ms, step, done) {
    const a = { t0: performance.now(), ms: reduced() ? Math.min(ms, 600) : ms, step, done };
    anims.add(a); kick(); return a;
  }

  function presetPress(i, down) {   // "Press to recall, hold to save"
    if (down) {
      holdSaved = false; clearTimeout(holdTimer);
      holdTimer = setTimeout(() => {
        holdSaved = true;
        S.cam.presets[S.cam.sel][i] = { ...S.cam.ptz[S.cam.sel] };
        S.presetSaved = true; clearTimeout(savedTimer);
        savedTimer = setTimeout(() => { S.presetSaved = false; render(); }, T.saved);
        render();
      }, T.hold);
    } else {
      clearTimeout(holdTimer);
      if (!holdSaved) recallPreset(i);
    }
  }
  function recallPreset(i, both, instant) {
    const cams = both ? Object.keys(CAMS) : [S.cam.sel];
    for (const c of cams) {
      const to = { ...S.cam.presets[c][i] };
      if (instant || reduced() || c !== S.cam.sel) S.cam.ptz[c] = to;
      else recall = { cam: c, from: { ...S.cam.ptz[c] }, to, t0: performance.now(), ms: 900 };
    }
    kick();
  }

  /* ---------------------------------------------------------------- input wiring */
  function wireButton(el, bind, kind) {
    const held = key => { pressed.add(key); renderPressed(key); };
    const free = key => { pressed.delete(key); renderPressed(key); };
    if (kind === 'toggle') { el.addEventListener('click', () => act(bind)); return; }
    let down = false;
    const start = () => { if (down) return; down = true; held(bind); if (kind === 'momentary') act(bind, true); };
    const end = fire => {
      if (!down) return; down = false;
      if (kind === 'momentary') { act(bind, false); free(bind); }
      else { free(bind); if (fire) act(bind); }
    };
    el.addEventListener('pointerdown', ev => {
      if (ev.button !== 0) return;
      try { el.setPointerCapture(ev.pointerId); } catch (e) { /* ignore */ }
      start();
    });
    el.addEventListener('pointerup', ev => {
      const r = el.getBoundingClientRect();
      end(ev.clientX >= r.left && ev.clientX <= r.right && ev.clientY >= r.top && ev.clientY <= r.bottom);
    });
    el.addEventListener('pointercancel', () => end(false));
    el.addEventListener('lostpointercapture', () => end(false));
    el.addEventListener('keydown', ev => { if ((ev.key === ' ' || ev.key === 'Enter') && !ev.repeat) { ev.preventDefault(); start(); } });
    el.addEventListener('keyup', ev => { if (ev.key === ' ' || ev.key === 'Enter') { ev.preventDefault(); end(true); } });
    el.addEventListener('blur', () => end(false));
    el.addEventListener('click', ev => ev.preventDefault());
    el.addEventListener('contextmenu', ev => ev.preventDefault());
  }
  function renderPressed(bind) { for (const el of byBind.get(bind) || []) el.classList.toggle('on', pressed.has(bind) || valueOf(bind)); }

  function gainRef(bind) {
    if (bind === 'vol.gain') return S.vol;
    const m = /^mic\.(\w+)\.gain$/.exec(bind); return m ? S.mic[m[1]] : null;
  }
  function wireFader(el, bind) {
    let drag = false;
    const setFrom = ev => {
      const r = el.getBoundingClientRect(), cap = 32 * (r.width / (parseFloat(el.style.width) || r.width));
      const p = (ev.clientX - r.left - cap / 2) / Math.max(1, r.width - cap);
      gainRef(bind).gain = gOf(Math.max(0, Math.min(1, p))); render();
    };
    el.addEventListener('pointerdown', ev => { if (ev.button !== 0) return; drag = true; try { el.setPointerCapture(ev.pointerId); } catch (e) { /* ignore */ } setFrom(ev); ev.preventDefault(); });
    el.addEventListener('pointermove', ev => { if (drag) setFrom(ev); });
    const stop = () => { drag = false; };
    el.addEventListener('pointerup', stop); el.addEventListener('pointercancel', stop); el.addEventListener('lostpointercapture', stop);
    el.addEventListener('keydown', ev => {
      const g = gainRef(bind); let v = g.gain;
      if (ev.key === 'ArrowRight' || ev.key === 'ArrowUp') v += 1;
      else if (ev.key === 'ArrowLeft' || ev.key === 'ArrowDown') v -= 1;
      else if (ev.key === 'PageUp') v += 6; else if (ev.key === 'PageDown') v -= 6;
      else if (ev.key === 'Home') v = DB.min; else if (ev.key === 'End') v = DB.max; else return;
      ev.preventDefault(); g.gain = Math.max(DB.min, Math.min(DB.max, Math.round(v * 10) / 10)); render();
    });
  }

  /* ---------------------------------------------------------------- feedback */
  function valueOf(bind) {
    const [a, b, c] = bind.split('.');
    switch (a) {
      case 'route': return b === 'all' ? Object.values(S.routes).every(r => r === c) : S.routes[b] === c;
      case 'disp': return c === 'on' ? S.disp[b].on : c === 'off' ? !S.disp[b].on : false;
      case 'vol': return b === 'mute' && S.vol.mute;
      case 'zoom': return S.zoomMicMute;
      case 'mic': return c === 'mute' && S.mic[b].mute;
      case 'nav': return S.page === b;
      case 'cam': return (b === 'sel' && S.cam.sel === c) || (b === 'privacy' && S.privacy);
      case 'av': return b === 'videomute' ? S.videoMute : S.camMute;
      case 'help': return b === 'now' && S.helpNow;
    }
    return false;
  }
  function layersVisible() {
    const up = S.power !== 'off', adv = up && S.mode === 'advanced';
    return {
      splash: S.power === 'off', warm: S.power === 'warming', cool: S.power === 'cooling',
      main: up, simple: up && S.mode === 'simple', advanced: adv,
      sources: adv && S.page === 'sources', room: adv && S.page === 'room', audio: adv && S.page === 'audio', cameras: adv && S.page === 'cameras',
      mixer: adv && S.page === 'audio' && S.mixer, help: up && S.help, shutdown: up && S.shutdown,
      presetSaved: adv && S.page === 'cameras' && S.presetSaved,
    };
  }

  let queued = false;
  function render() { if (!queued) { queued = true; requestAnimationFrame(() => { queued = false; paint(); }); } }
  function paint() {
    const vis = layersVisible();
    for (const [k, el] of Object.entries(layerEl)) el.hidden = !vis[k];
    for (const [bind, els] of byBind) {
      const [a, b, c] = bind.split('.');
      const on = pressed.has(bind) || valueOf(bind);
      for (const el of els) {
        if (el.tagName === 'BUTTON') {
          el.classList.toggle('on', on);
          if (el.dataset.kind === 'toggle') el.setAttribute('aria-pressed', String(on));
          if (a === 'disp') el.hidden = !!S.disp[b].busy;
          if (bind === 'mode.toggle') el.setAttribute('aria-label', S.mode === 'simple' ? 'Hance Auditorium. Switch to Advanced controls' : 'Hance Auditorium. Switch to Simple controls');
        } else if (el.classList.contains('m')) {
          let p = 0;
          if (a === 'disp') { el.hidden = !S.disp[b].busy; p = S.disp[b].p; }
          else p = S.sysP;
          el.firstChild.style.width = (p * 100).toFixed(1) + '%';
          el.setAttribute('aria-valuenow', String(Math.round(p * 100)));
        } else if (el.classList.contains('f')) {
          const g = gainRef(bind);
          el.style.setProperty('--p', pOf(g.gain).toFixed(4));
          el.setAttribute('aria-valuenow', String(g.gain)); el.setAttribute('aria-valuetext', db(g.gain));
        }
      }
    }
    if (vis.cameras) { paintMedia(true); feedDirty = true; kick(); }
    pushScene();
    paintStatus();
    listeners.forEach(fn => fn(S));
  }

  /* ---------------------------------------------------------------- 3D hooks */
  let lastPush = '';
  function pushScene() {
    if (!scene || !engaged) return;
    const P = S.disp.proj;
    const on = P.on && !(P.busy < 0);
    const state = { on, mute: S.videoMute, source: S.routes.proj === 'zoom' ? 'zoom' : 'presentation', screen: S.screen === 'down',
      volume: S.vol.mute ? 0 : pOf(S.vol.gain) };
    const key = JSON.stringify(state); if (key === lastPush) return; lastPush = key;
    scene.setProjector && scene.setProjector({ on: state.on, mute: state.mute, source: state.source });
    scene.setScreenDeployed && scene.setScreenDeployed(state.screen);
    scene.setVolume && scene.setVolume(state.volume);
  }
  // The viewer's own Presentation / Zoom switch talks back to the panel
  window.addEventListener('c2146:screen', ev => {
    if (S.power !== 'on') return;
    const z = ev.detail === 'zoom';
    if (z) S.routes.proj = 'zoom'; else if (S.routes.proj === 'zoom') S.routes.proj = 'pc';
    Object.assign(S.disp.proj, { on: true, busy: 0, p: 0 }); S.videoMute = false;
    lastPush = ''; render();
  });

  /* ---------------------------------------------------------------- camera preview (live render from the 3D model) */
  let feed = null, feedDirty = true, lastFeed = 0, onScreen = true;
  new IntersectionObserver(es => { onScreen = es[0].isIntersecting; if (onScreen) kick(); }).observe(screen);
  function paintMedia(visible) {
    if (!mediaEl || !visible) return;
    const cam = CAMS[S.cam.sel];
    mediaTag.textContent = cam.tag;
    if (!feed && scene && scene.cameraFeed && (!scene.ready || scene.ready())) {
      feed = scene.cameraFeed();
      if (feed && feed.canvas) mediaEl.insertBefore(feed.canvas, mediaEl.firstChild);
    }
    let msg = '';
    if (S.privacy) msg = 'Privacy on';
    else if (S.camMute) msg = 'Camera muted';
    else if (!feed) msg = scene && scene.ready && !scene.ready() ? 'Connecting to the camera…' : 'Camera preview needs the 3D model, which didn’t load in this browser.';
    mediaMsg.textContent = msg; mediaMsg.hidden = !msg;
    if (feed && feed.canvas) feed.canvas.style.visibility = msg ? 'hidden' : 'visible';
    mediaTag.hidden = !!msg;
  }

  /* ---------------------------------------------------------------- ticker: progress bars, PTZ motion, preview frames */
  let raf = 0, idle = 0, lastT = 0, inTick = false, again = false;
  function kick() {
    if (inTick) { again = true; return; }
    if (idle) { clearTimeout(idle); idle = 0; }
    if (!raf) { lastT = performance.now(); raf = requestAnimationFrame(tick); }
  }
  function tick(now) {
    raf = 0; inTick = true; again = false;
    const dt = Math.max(0, Math.min(0.1, (now - lastT) / 1000)); lastT = now;
    let busy = false, changed = false;
    for (const a of [...anims]) {
      const p = Math.min(1, (now - a.t0) / a.ms); a.step(p); changed = true;
      if (p >= 1) { anims.delete(a); a.done(); } else busy = true;
    }
    const P = S.cam.ptz[S.cam.sel];
    if (moving.size) {
      if (moving.has('pan_left')) P.pan = Math.min(PTZ.panMax, P.pan + PTZ.panRate * dt / P.zoom);
      if (moving.has('pan_right')) P.pan = Math.max(-PTZ.panMax, P.pan - PTZ.panRate * dt / P.zoom);
      if (moving.has('tilt_up')) P.tilt = Math.min(PTZ.tiltMax, P.tilt + PTZ.tiltRate * dt / P.zoom);
      if (moving.has('tilt_down')) P.tilt = Math.max(PTZ.tiltMin, P.tilt - PTZ.tiltRate * dt / P.zoom);
      if (moving.has('zoom_in')) P.zoom = Math.min(PTZ.zoomMax, P.zoom * Math.pow(PTZ.zoomRate, dt));
      if (moving.has('zoom_out')) P.zoom = Math.max(1, P.zoom / Math.pow(PTZ.zoomRate, dt));
      feedDirty = true; busy = true;
    }
    if (recall) {
      const k = Math.min(1, (now - recall.t0) / recall.ms), e = k < .5 ? 2 * k * k : 1 - Math.pow(-2 * k + 2, 2) / 2;
      const Q = S.cam.ptz[recall.cam];
      for (const f of ['pan', 'tilt', 'zoom']) Q[f] = recall.from[f] + (recall.to[f] - recall.from[f]) * e;
      feedDirty = true; if (k >= 1) recall = null; else busy = true;
    }
    if (changed) paint();
    const watching = !layerEl.cameras.hidden && onScreen && !document.hidden;
    if (watching) {
      if (!feed && scene && scene.cameraFeed) paintMedia(true);
      if (feed && feed.render && !S.privacy && !S.camMute && (feedDirty || now - lastFeed > 3000)) {
        const r = mediaEl.getBoundingClientRect(), dpr = Math.min(2, window.devicePixelRatio || 1);
        feed.render(CAMS[S.cam.sel].view, S.cam.ptz[S.cam.sel], Math.round(r.width * dpr), Math.round(r.height * dpr));
        feedDirty = false; lastFeed = now;
      }
    }
    inTick = false;
    if (busy || again) raf = requestAnimationFrame(tick);
    else if (watching) idle = setTimeout(() => { idle = 0; kick(); }, 1000);   // slow heartbeat so the preview follows the model
  }

  /* ---------------------------------------------------------------- status readout */
  function paintStatus() {
    if (!statusEl) return;
    const pct = p => Math.round(p * 100) + '%';
    const disp = d => {
      if (S.power !== 'on') return 'Off';
      const D = S.disp[d];
      if (D.busy) return (D.busy > 0 ? 'Warming up ' : 'Cooling down ') + pct(D.p);
      if (!D.on) return 'Off';
      return SRC[S.routes[d]] + (S.videoMute ? ', video muted' : '');
    };
    const mic = m => S.mic[m].mute ? 'muted' : db(S.mic[m].gain);
    const sys = { off: 'Off, on the start screen', warming: 'Starting up ' + pct(S.sysP), on: S.mode === 'simple' ? 'On, Simple controls' : 'On, Advanced: ' + PAGE[S.page], cooling: 'Shutting down ' + pct(S.sysP) }[S.power];
    const cam = CAMS[S.cam.sel].name + (S.privacy ? ', privacy on' : '') + (S.camMute ? ', muted' : '');
    const rows = [
      ['System', sys], ['Projector', disp('proj')], ['Left display', disp('left')], ['Right display', disp('right')],
      ['Screen', S.screen === 'down' ? 'Down' : 'Up'], ['Room volume', S.vol.mute ? 'Muted' : db(S.vol.gain)],
      ['Zoom mic', S.zoomMicMute ? 'Muted' : 'Live'],
      ['Wireless mics', S.mixer ? 'Handed to the mixer' : `Lapel ${mic('lapel')}, handheld ${mic('handheld')}`],
      ['Ceiling mic', S.mic.ceiling.mute ? 'Muted' : 'Live'], ['Zoom camera', cam],
    ];
    const html = rows.map(([k, v]) => `<div><dt>${k}</dt><dd>${esc(v)}</dd></div>`).join('');
    if (statusEl.innerHTML !== html) statusEl.innerHTML = html;
  }

  /* ---------------------------------------------------------------- api */
  function reset() {
    anims.clear(); moving.clear(); pressed.clear(); recall = null;
    clearTimeout(holdTimer); clearTimeout(savedTimer); clearTimeout(toastTimer); toastEl.classList.remove('show');
    S = fresh();
    if (scene && engaged) { scene.setProjector && scene.setProjector({ on: true, mute: false }); scene.setScreenDeployed && scene.setScreenDeployed(true); }
    engaged = false; lastPush = '';
    paint();
  }
  paint();
  return {
    stage, reset, fit,
    state: () => JSON.parse(JSON.stringify(S)),
    press: (bind, ms = 0) => new Promise(res => {        // for tests: press a control by its binding
      const el = (byBind.get(bind) || []).find(x => x.offsetParent !== null) || (byBind.get(bind) || [])[0];
      if (!el) return res(false);
      engage();
      const kind = el.dataset.kind;
      if (kind === 'toggle') { el.click(); return res(true); }
      pressed.add(bind); if (kind === 'momentary') act(bind, true); renderPressed(bind);
      setTimeout(() => { if (kind === 'momentary') act(bind, false); pressed.delete(bind); if (kind !== 'momentary') act(bind); renderPressed(bind); res(true); }, ms);
    }),
    onChange: fn => { listeners.add(fn); return () => listeners.delete(fn); },
  };
}
